default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  password: postgres
  username: postgres

development:
  <<: *default
  database: tempora_dev

test:
  <<: *default
  database: tempora_test

production:
  <<: *default
  database: tempora_prod
